---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp1-deployment
 labels:
   app: myapp2
spec:
 replicas: 1
 selector:
   matchLabels:
     app: myapp2
 template:
   metadata:
     labels:
       app: myapp2
   spec:
     containers:
     - name: myapp2
       image: demok8sdevops1.azurecr.io/myapp2:latest 
       ports:
       - containerPort: 4001
     imagePullSecrets:
     - name: kama-kama
---
apiVersion: v1
kind: Service
metadata:
 name: myapp2
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 4001
 selector:
   app: myapp2


