apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
  labels:
    app: myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: demok8sdevops1.azurecr.io/myapp1:latest
        ports:
        - containerPort: 4001
     imagePullSecrets:
      - name: kama-kama
