---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp3-deployment
 labels:
   app: myapp3
spec:
 replicas: 1
 selector:
   matchLabels:
     app: myapp3
 template:
   metadata:
     labels:
       app: myapp3
   spec:
     containers:
     - name: myapp3
       image: containerk8s.azurecr.io/myapp3:latest 
       ports:
       - containerPort: 4001
     imagePullSecrets:
     - name: kama-kama
---
apiVersion: v1
kind: Service
metadata:
 name: myapp3
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 4001
 selector:
   app: myapp3


